# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "log-generator.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ include "log-generator.name" . }}